server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
      #none: The default for MySQL. No change is made to the database structure.
      #update: Hibernate changes the database according to the given entity structures.
      #create: Creates the database every time but does not drop it on close.
      #create-drop: Creates the database and drops it when SessionFactory closes.
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tradesys
    username: tradedb
    password: tradedbsystem
