server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
      #none: The default for MySQL. No change is made to the database structure.
      #update: Hibernate changes the database according to the given entity structures.
      #create: Creates the database every time but does not drop it on close.
      #create-drop: Creates the database and drops it when SessionFactory closes.
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tradesys
    username: tradedb
    password: tradedbsystem
    #Configurações de conexão com a instância do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: gecapsp
    password: tradesystem
    #Nome exchange a ser criado pelo projeto no output
  cloud:
    stream:
      bindings:
        output:
          destination: mensagem-simples
        canal-mensage:
          destination: teste

          #para consumer
        input:
          destination: canal-mensagem
          group: teste